---
title: "Aula4"
author: "Leonardo G Sanches"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Estruturas de controle
## IF
if(condição){resultado}else{resultado}
```{r}
x = 4
if(x>3){y=10}else{y=0}
y
y=if(x>3){10}else{0}
y
```
## For
for(valores){resultados}
```{r}
for(i in 1:10){print(i)}

#Lista
b <- NULL
for(i in 1:10){
  a <- i
  b[i] <- a
}
b
```
```{r}
set.seed(143)
dados <- round(rnorm(10,50,10),2)

sim <- matrix(,ncol=25,nrow=100)
media <- NA
desvio <- NA
sim_inicio <- NA

for(i in 2:nrow(sim)){
  set.seed(143+i)
  sim_inicio <- rnorm(ncol(sim), mean=mean(dados),sd=sd(dados))
  sim[1,] <- sim_inicio
  media[1]<- mean(sim[1,])
  desvio <- sd(sim[1,])
  sim[i,] <- rnorm(ncol(sim),mean=mean(sim[i-1,]),sd=sd(sim[i-1,]))
  media[i] <- mean(sim[i,])
  desvio[i] <- sd(sim[i,])
}
sim
```


```{r}
rbind(media,desvio)
plot(media)
```
## While
```{r}
count = 0
while(count<3){
  print(count)
  count=count+1
}
```
##  Next
```{r}
for (i in 1:30){
  if(i<=20){next}
  print(i)
}
```


## Defininfo Funçõpes
f <- function(argumento){
faça algo
}

Deixar a função sem argumentos, mostra o código
Colocar ponto de interrogação abre a janela de help

```{r}
?lm
```
```{r}
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
lm.D90 <- lm(weight ~ group - 1) # omitting intercept

anova(lm.D9)
summary(lm.D90)

opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0))
plot(lm.D9, las = 1)      # Residuals, Fitted, ...
par(opar)
```
## Construindo uma função
```{r}
Z <- 0.95
Pi <- 0.5
e <- 0.05
N <- 45000
n_inicial <- qnorm(1-(1-Z)/2)^2*Pi*(1-Pi)/e^2
n_final <- N*n_inicial/(N+n_inicial)
#ceiling(n_inicial)
ceiling(cbind(n_inicial,n_final))

amostra_prop <- function(nc=95,pi=0.5,erro=5,N=999999999){
  Z <- nc/100
  e <- erro/100
  Pi <- pi/100
  n_inicial <- qnorm(1-(1-Z)/2)^2*Pi*(1-Pi)/e^2
  n_final <- N*n_inicial/(N+n_inicial)
  ceiling(cbind(n_inicial,n_final))
}
amostra_prop(N=45000)

```

